version: '3.8'

services:
  # Service pour le frontend React
  client:
    build: ./client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - server
    environment:
      - REACT_APP_API_URL=http://localhost:5000/api
    stdin_open: true # Pour le hot-reloading de Create React App

  # Service pour le backend Node.js/Express
  server:
    build: ./server
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app
      - /app/node_modules
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/mycollect
      - JWT_SECRET=votre_secret_jwt_temporaire
      - NODE_ENV=development

  # Service pour MongoDB
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: